esphome:
  name: enervent
  comment: Garage AHU - Enervent Pingvin EDA

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Enervent Fallback Hotspot"
    password: !secret esphome_fallback_wifi_password

captive_portal:


## UART definitions
uart:
  id: mod_bus
  tx_pin: D8
  rx_pin: D7
  baud_rate: 19200
  stop_bits: 1
  parity: NONE

modbus:
  id: modbus1

modbus_controller:
  - id: enervent
    address: 0x1
    modbus_id: modbus1
    setup_priority: -10


switch:
## coils:
  - platform: modbus_controller
    modbus_controller_id: enervent
    id: garage_stop
    name: "Garage - STOP"
    register_type: coil
    address: 0
    bitmask: 1
  - platform: modbus_controller
    modbus_controller_id: enervent
    id: garage_away
    name: "Garage - Away"
    register_type: coil
    address: 1
    bitmask: 1
  - platform: modbus_controller
    modbus_controller_id: enervent
    id: garage_overpressure
    name: "Garage - Overpressure"
    register_type: coil
    address: 3
    bitmask: 1
  - platform: modbus_controller
    modbus_controller_id: enervent
    id: garage_manualboost
    name: "Garage - Manual Boost"
    register_type: coil
    address: 10
    bitmask: 1
  - platform: modbus_controller
    modbus_controller_id: enervent
    id: garage_summernightcooling
    name: "Garage - Summer Night Cooling"
    register_type: coil
    address: 12
    bitmask: 1

sensor:

## temperature sensors:
  - platform: modbus_controller
    modbus_controller_id: enervent
    name: "Garage - Fresh Air"
    id: garage_freshair
    register_type: holding
    address: 6
    device_class: temperature
    unit_of_measurement: "C"
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: enervent
    name: "Garage - Supply Air after HRC"
    id: garage_supplyhrcair
    register_type: holding
    address: 7
    device_class: temperature
    unit_of_measurement: "C"
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: enervent
    name: "Garage - Supply Air"
    id: garage_supplyair
    register_type: holding
    address: 8
    device_class: temperature
    unit_of_measurement: "C"
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: enervent
    name: "Garage - Waste Air"
    id: garage_wasteair
    register_type: holding
    address: 9
    device_class: temperature
    unit_of_measurement: "C"
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: enervent
    name: "Garage - Extract Air"
    id: garage_extract
    register_type: holding
    address: 10
    device_class: temperature
    unit_of_measurement: "C"
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

## Humidity sensor:
  - platform: modbus_controller
    modbus_controller_id: enervent
    name: "Garage - Exhaust Humidity"
    id: garage_extract_humidity
    register_type: holding
    address: 13
    device_class: humidity
    unit_of_measurement: "%RH"
    value_type: U_WORD

## HRC efficiency
  - platform: modbus_controller
    modbus_controller_id: enervent
    name: "Garage - HRC Supply %"
    id: garage_hrcsupply
    register_type: holding
    address: 29
    device_class: power_factor
    unit_of_measurement: "%"
    value_type: U_WORD
  - platform: modbus_controller
    modbus_controller_id: enervent
    name: "Garage - HRC Extract %"
    id: garage_hrcextract
    register_type: holding
    address: 30
    device_class: power_factor
    unit_of_measurement: "%"
    value_type: U_WORD